import Head from 'next/head'
import { Inter } from 'next/font/google'
import indexSass from '../styles/index.module.scss'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="container">
        <div className="row">
          <div className="col-3"></div>
          <div className="col-6"></div> 
          <div className="col-3"></div>
        </div>
      </div>

      <script src="../styles/node_modules/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    </>
  )
}
